# Generated by Django 3.2.7 on 2021-09-15 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeVideoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('video_url', models.CharField(max_length=500)),
                ('video_id', models.CharField(max_length=500)),
                ('published_date', models.CharField(max_length=500)),
            ],
        ),
    ]
